[build]
  functions = "netlify/functions"
  command   = "echo 'nothing to build'"
  
[[redirects]]
  # send *all* traffic to functions
  from    = "/*"
  to      = "/.netlify/functions/server"
  status  = 200
